// Copyright (c) 2023 CurtinFRC
// Open Source Software, you can modify it according to the terms
// of the MIT License at the root of this project

/*
  Do not edit this file
  Go to Robot.cpp
*/

#include "Robot.h"
#include "utils/RobotStartup.h"

WOMBAT_ROBOT_MAIN(Robot);
