version: 2
- package-ecosystem: "gradle"
  directory: "/"
  schedule: 
    interval: "daily"
- package-ecosystem: "gradle"
  directory: "/wombat"
  schedule:
    interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

